### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by fi0** [JesusFreke/fscad#1]
What's the recommended workflow for automating the  'edit python code -> view 3D model in fusion 360'? I'm on mac so I didnt try the intellij plugin. I'm looking for ways to automate that in the terminal. thank you!

**Comment by JesusFreke** [comment]
There's no good way to do it from a terminal that I'm aware of. The intellij plugin essentially attaches to the fusion 360 process and injects some python code that then loads the script and runs it. Under the hood, intellij is using pydevd to do all that, so it may be possible to write a small loader program that you can call from a terminal that uses pydevd to do the same thing.

Personally, I make heavy use of the intellij plugin of course. All my development on a design using fscad is done in IDEA, and I run it directly from there.

But other than that, you pretty much have to add it as a script in fusion and run it from the "scripts and add-ins" thing.

**Comment by fi0** [comment]
Thank you! I might instead work on mac version of your intellij plugin.

**Comment by JesusFreke** [comment]
I've left a comment on the "mac support" issue over in that repository with some ideas about how to get started. If you have any questions or anything, feel free to comment on that issue.
