### ISSUE TITLE
shell command

### ISSUE THREAD

**Issue by fi0** [JesusFreke/fscad#2]
Is there a shell command? Or, how should I add it? Thank you!

**Comment by JesusFreke** [comment]
There isn't atm, but it probably wouldn't be too hard to add. You could look at the implementation of something like, maybe, SplitFace or Extrude.

**Comment by fi0** [comment]
Thank you! I'll look into them.

**Comment by JesusFreke** [comment]
np! I was looking at your profile and happened to notice the CadQuery project - looks like a very interesting project! I wasn't previously aware of that.
